import { TailwindcssPatcher } from 'tailwindcss-patch'
import cfg from "./tailwindcss-mangle.config.js"
const twPatcher = new TailwindcssPatcher(
    cfg
)
// do patch
twPatcher.patch()
// get all contexts at runtime
twPatcher.getContexts()
// get all class generated by tailwindcss utilities
console.log(twPatcher.getClassSet())